// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostStatus } from "./PostStatus";

/**
 * Request body for `POST /posts`.
 */
export type CreatePost = {
  slug: string;
  title: string;
  summary: string | null;
  body_adoc: string;
  status: PostStatus;
};
