// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostStatus } from "./PostStatus";

/**
 * A single blog post, mapping one-to-one to a row of the `posts`
 * table defined in `migrations/0001_init.sql`.
 */
export type Post = {
  /**
   * Primary key of the row (`INTEGER PRIMARY KEY AUTOINCREMENT`).
   */
  id: number;
  /**
   * Stable public identifier that never changes and is safe to expose.
   *
   * This identifier is generated independently of timestamps so it
   * does not leak creation order or publication timing. Use it for
   * stable hyperlinks and long-lived external references.
   */
  public_id: string;
  /**
   * Human-readable URL slug for the post.
   *
   * Backed by a `UNIQUE` constraint at the database level and used
   * for canonical friendly URLs. Unlike [`Post::public_id`], this
   * value may change over time to improve readability.
   */
  slug: string;
  /**
   * Display title shown in the post header and in listings.
   */
  title: string;
  /**
   * Optional one-line teaser for listings and social previews.
   *
   * `None` when the author has not provided one; the frontend is
   * free to fall back to a body excerpt or omit the field entirely.
   */
  summary: string | null;
  /**
   * Post body in AsciiDoc source form.
   *
   * This is the authoritative representation of the post content —
   * all rendered artifacts (static HTML, RSS, search index, ...)
   * are regenerable from `body_adoc` alone. The API never performs
   * AsciiDoc → HTML conversion server-side, so clients must run
   * their own renderer.
   */
  body_adoc: string;
  /**
   * Visibility state of the post. See [`PostStatus`] for the
   * meaning of each variant.
   */
  status: PostStatus;
  /**
   * Timestamp at which the post first transitioned to
   * [`PostStatus::Public`], or `None` if it has never been
   * published.
   *
   * Stored and transmitted as an RFC 3339 string in UTC (e.g.
   * `2026-04-12T02:04:09Z`), parsed into [`DateTime<Utc>`] on the
   * Rust side by chrono's default serde impl and re-exported to
   * TypeScript as `string` via ts-rs's `chrono-impl` feature.
   */
  published_at: string | null;
  /**
   * Timestamp of the row's initial insertion.
   *
   * Populated by the SQLite `DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ',
   * 'now'))` clause on the `posts.created_at` column, so inserts
   * never need to pass it explicitly. Immutable after creation.
   */
  created_at: string;
  /**
   * Timestamp of the most recent successful update to the row.
   *
   * Populated by the same SQLite `DEFAULT` expression as
   * `created_at` on insertion, but is *not* refreshed automatically
   * on `UPDATE` — there is no database trigger, so any write
   * handler that mutates a row must set `updated_at` explicitly.
   */
  updated_at: string;
  /**
   * Monotonic edit counter that starts at `1` on insertion and is
   * bumped by every successful update.
   *
   * Included in read responses so that clients can cache by
   * `(id, revision_no)` and so that future write handlers can use
   * it as an optimistic-concurrency token. Like `updated_at`, it
   * is maintained by the application layer rather than a trigger.
   */
  revision_no: number;
};
