// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PostSummary = {
  public_id: string;
  slug: string;
  title: string;
  summary: string | null;
  published_at: string | null;
};
