// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary data for the public post listing endpoint.
 *
 * This is intentionally smaller than [`Post`]: callers that only need
 * the index view should not pay to transfer or deserialize the full
 * AsciiDoc source for every post.
 */
export type PostSummary = {
  public_id: string;
  slug: string;
  title: string;
  summary: string | null;
  published_at: string | null;
};
