// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Visibility lifecycle of a [`Post`].
 *
 * Enforced at the database level by a `CHECK (status IN ('draft',
 * 'private', 'public', 'trashed'))` constraint on the `posts.status`
 * column, so any value outside this enum is rejected before it
 * reaches Rust. The four-state lifecycle is intentionally minimal —
 * anything more elaborate (scheduled publishing, embargoed drafts,
 * per-reader access control) can be layered on later without a
 * wire-format change.
 */
export type PostStatus = "draft" | "private" | "public" | "trashed";
