// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostStatus } from "./PostStatus";

export type Post = {
  id: number;
  public_id: string;
  slug: string;
  title: string;
  summary: string | null;
  body_adoc: string;
  status: PostStatus;
  published_at: string | null;
  created_at: string;
  updated_at: string;
  revision_no: number;
};
