// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostStatus } from "./PostStatus";

/**
 * Request body for `PUT /posts/by-slug/{slug}`.
 *
 * Every field except `revision_no` is optional — only the fields
 * present in the request payload are updated. `revision_no` is
 * required and acts as an optimistic-concurrency token: the update
 * succeeds only when the value matches the current row.
 */
export type UpdatePost = {
  slug: string | null;
  title: string | null;
  summary: string | null;
  body_adoc: string | null;
  status: PostStatus | null;
  revision_no: number;
};
