// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostStatus } from "./PostStatus";

export type UpdatePost = {
  slug: string | null;
  title: string | null;
  summary: string | null;
  body_adoc: string | null;
  status: PostStatus | null;
  revision_no: number;
};
